# Generated by Django 3.0.8 on 2021-01-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='file'),
        ),
    ]
